<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class Chapter1100pricingTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('chapter1100pricing')->delete();
        
        \DB::table('chapter1100pricing')->insert(array (
            
            1 => 
            array (
                'id' => '1',
                'geller_sku' => '110000',
                'retail_price' => '$18 ',
                'optionable' => '1',
                'major_item' => 'Battery',
                'description' => '1 Year Guarantee Watch Battery, snap back',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => 'Shaista: Figure cost at 50%',
                'created_at' => '',
                'updated_at' => '',
            ),
            2 => 
            array (
                'id' => '2',
                'geller_sku' => '110001',
                'retail_price' => '$27 ',
                'optionable' => '1',
                'major_item' => 'Battery',
                'description' => '1 Year Guarantee Watch Battery,screw back',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => 'This needs to be editable by jewelry store. This is from an indendant',
                'created_at' => '',
                'updated_at' => '',
            ),
            3 => 
            array (
                'id' => '3',
                'geller_sku' => '110002',
                'retail_price' => '$27 ',
                'optionable' => '1',
                'major_item' => 'Battery',
                'description' => '3 Year Guarantee Watch Battery, snap back',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '"vendor, not Stuller, where e can pull costs."',
                'created_at' => '',
                'updated_at' => '',
            ),
            4 => 
            array (
                'id' => '4',
                'geller_sku' => '110003',
                'retail_price' => '$36 ',
                'optionable' => '1',
                'major_item' => 'Battery',
                'description' => '3 Year Guarantee Watch Battery,screw back',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            5 => 
            array (
                'id' => '5',
                'geller_sku' => '110004',
                'retail_price' => '$54 ',
                'optionable' => '1',
                'major_item' => 'Battery',
                'description' => 'Lifetime Watch Battery',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            6 => 
            array (
                'id' => '6',
                'geller_sku' => '110005',
                'retail_price' => '$63 ',
                'optionable' => '1',
                'major_item' => 'Battery',
                'description' => 'Lifetime Watch Battery screw back',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            7 => 
            array (
                'id' => '7',
                'geller_sku' => '110006',
                'retail_price' => '$27 ',
                'optionable' => '1',
                'major_item' => 'Battery',
                'description' => 'Chronograph 1 yr battery inc reset/zero match',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            8 => 
            array (
                'id' => '8',
                'geller_sku' => '110007',
                'retail_price' => '$36 ',
                'optionable' => '1',
                'major_item' => 'Battery',
                'description' => 'Chronograph 3 yr battery inc,reset/zero match',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            9 => 
            array (
                'id' => '9',
                'geller_sku' => '110008',
                'retail_price' => '$63 ',
                'optionable' => '1',
                'major_item' => 'Battery',
                'description' => 'Chronograph lifetime battery,inc reset/zero match',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            10 => 
            array (
                'id' => '10',
                'geller_sku' => '110009',
                'retail_price' => '$153 ',
                'optionable' => '1',
                'major_item' => 'Battery',
            'description' => 'Split Design Cases (Ex: Ebel) 1 Year Battery',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            11 => 
            array (
                'id' => '11',
                'geller_sku' => '110010',
                'retail_price' => '',
                'optionable' => '1',
                'major_item' => 'Battery',
                'description' => 'Split Design Cases (Ex: Ebel) Dual Watch Battery',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '50',
                'chapter1100SKUs' => '110009',
                'is_estimated' => '0',
                'note' => 'Add 50% to charges above',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            12 => 
            array (
                'id' => '12',
                'geller_sku' => '110011',
                'retail_price' => '$44 ',
                'optionable' => '1',
                'major_item' => 'Battery',
                'description' => 'Car Remote Battery,1 Year Guarantee',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            13 => 
            array (
                'id' => '13',
                'geller_sku' => '110012',
                'retail_price' => '$117 ',
                'optionable' => '1',
                'major_item' => 'Battery',
            'description' => 'Watch Spa & Lifetime Battery(Battery; Clean Case; Reseal; Gaskets)',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            14 => 
            array (
                'id' => '14',
                'geller_sku' => '110013',
                'retail_price' => '$153 ',
                'optionable' => '1',
                'major_item' => 'Battery',
            'description' => 'Deluxe Watch Spa & Lifetime Battery(Battery; Clean Case; Reseal; Gaskets; New Crystal)',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            15 => 
            array (
                'id' => '15',
                'geller_sku' => '110014',
                'retail_price' => '$9 ',
                'optionable' => '0',
                'major_item' => 'Battery',
                'description' => 'Remove the watch band',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '1',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            16 => 
            array (
                'id' => '16',
                'geller_sku' => '110015',
                'retail_price' => '$9 ',
                'optionable' => '0',
                'major_item' => 'Battery',
                'description' => 'Sports Watches have sealed back, some have multiple screws',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '1',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            17 => 
            array (
                'id' => '17',
                'geller_sku' => '110016',
                'retail_price' => '$18 ',
                'optionable' => '0',
                'major_item' => 'Battery',
            'description' => 'Special Design Cases(EX: Rado,Baume Mercier)',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '1',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            18 => 
            array (
                'id' => '18',
                'geller_sku' => '110017',
                'retail_price' => '$90 ',
                'optionable' => '0',
                'major_item' => 'Battery',
            'description' => 'Split Stem Design Cases(EX: Ebel)',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '1',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            19 => 
            array (
                'id' => '19',
                'geller_sku' => '110018',
                'retail_price' => '$18 ',
                'optionable' => '0',
                'major_item' => 'Battery',
                'description' => 'Red Hard Case Gasket',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '1',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => 'extra charge for this gasket',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            20 => 
            array (
                'id' => '20',
                'geller_sku' => '110040',
                'retail_price' => '$38 ',
                'optionable' => '1',
                'major_item' => 'Crystal',
                'description' => 'Buff or Polish a plastic crystal',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            21 => 
            array (
                'id' => '21',
                'geller_sku' => '110041',
                'retail_price' => '$63 ',
                'optionable' => '1',
                'major_item' => 'Crystal',
                'description' => 'Flat,round generic mineral',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            22 => 
            array (
                'id' => '22',
                'geller_sku' => '110042',
                'retail_price' => '$75 ',
                'optionable' => '1',
                'major_item' => 'Crystal',
                'description' => 'Thick,round,mineral crystal',
                'each_additional' => '',
                'price_criteria_item' => '',
            'thickness' => '2mm+ thick (Fossils as well)',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            23 => 
            array (
                'id' => '23',
                'geller_sku' => '110043',
                'retail_price' => '$88 ',
                'optionable' => '1',
                'major_item' => 'Crystal',
                'description' => 'Domed mineral',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            24 => 
            array (
                'id' => '24',
                'geller_sku' => '110044',
                'retail_price' => '$100 ',
                'optionable' => '1',
                'major_item' => 'Crystal',
                'description' => 'Flat,Round,Sapphire',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '1.0mm thick',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            25 => 
            array (
                'id' => '25',
                'geller_sku' => '110045',
                'retail_price' => '$150 ',
                'optionable' => '1',
                'major_item' => 'Crystal',
                'description' => 'Flat,Round,Sapphire',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '1.5mm thick',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            26 => 
            array (
                'id' => '26',
                'geller_sku' => '110046',
                'retail_price' => '$188 ',
                'optionable' => '1',
                'major_item' => 'Crystal',
                'description' => 'Flat,Round,Sapphire',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '2.0mm thick',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            27 => 
            array (
                'id' => '27',
                'geller_sku' => '110047',
                'retail_price' => '$63 ',
                'optionable' => '1',
                'major_item' => 'Crystal',
                'description' => 'Standard Acrylic crystal,plastic',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            28 => 
            array (
                'id' => '28',
                'geller_sku' => '110048',
                'retail_price' => '$625 ',
                'optionable' => '1',
                'major_item' => 'Crystal',
                'description' => 'Rolex Acrylic,Plastic',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            29 => 
            array (
                'id' => '29',
                'geller_sku' => '110049',
                'retail_price' => '$1,375 ',
                'optionable' => '1',
                'major_item' => 'Crystal',
                'description' => 'Rolex Sapphire ',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            30 => 
            array (
                'id' => '30',
                'geller_sku' => '110050',
                'retail_price' => '$375 ',
                'optionable' => '1',
                'major_item' => 'Crystal',
                'description' => 'Regular Domed Sapphire ',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            31 => 
            array (
                'id' => '31',
                'geller_sku' => '110051',
                'retail_price' => '$163 ',
                'optionable' => '1',
                'major_item' => 'Crystal',
                'description' => 'Fancy cut mineral ',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            32 => 
            array (
                'id' => '32',
                'geller_sku' => '110052',
                'retail_price' => '$125 ',
                'optionable' => '1',
                'major_item' => 'Crystal',
                'description' => 'OEM crystals,Seiko, citizen etc.',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            33 => 
            array (
                'id' => '33',
                'geller_sku' => '110053',
                'retail_price' => '$38 ',
                'optionable' => '1',
                'major_item' => 'Dial Service',
                'description' => 'Reattach markers',
                'each_additional' => '110054',
                'price_criteria_item' => 'Reattach marker',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            34 => 
            array (
                'id' => '34',
                'geller_sku' => '110054',
                'retail_price' => '$19 ',
                'optionable' => '0',
                'major_item' => 'Dial Service',
                'description' => 'Reattch markers',
                'each_additional' => ' ea additional one attached"',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            35 => 
            array (
                'id' => '35',
                'geller_sku' => '110055',
                'retail_price' => '$88 ',
                'optionable' => '1',
                'major_item' => 'Dial Service',
                'description' => 'Attach dial feet ti dial, uses a laser',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            36 => 
            array (
                'id' => '36',
                'geller_sku' => '110056',
                'retail_price' => '$45 ',
                'optionable' => '1',
                'major_item' => 'Dial Service',
                'description' => 'Dial wih Day/Date Attachment',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            37 => 
            array (
                'id' => '37',
                'geller_sku' => '110057',
                'retail_price' => '$25 ',
                'optionable' => '1',
                'major_item' => 'Dial Service',
                'description' => 'Reset Hands basic',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            38 => 
            array (
                'id' => '38',
                'geller_sku' => '110058',
                'retail_price' => '$38 ',
                'optionable' => '1',
                'major_item' => 'Dial Service',
                'description' => 'Reset Hands chronograph',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            39 => 
            array (
                'id' => '39',
                'geller_sku' => '110059',
                'retail_price' => 'By Estimate Only',
                'optionable' => '1',
                'major_item' => 'Dial Service',
                'description' => 'Original Manufacturer Hands ',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            40 => 
            array (
                'id' => '40',
                'geller_sku' => '110060',
                'retail_price' => '$63 ',
                'optionable' => '1',
                'major_item' => 'Dial Service',
                'description' => 'General hands Basic',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            41 => 
            array (
                'id' => '41',
                'geller_sku' => '110061',
                'retail_price' => '$338 ',
                'optionable' => '1',
                'major_item' => 'Dial Service',
                'description' => 'Complete Dial Refinishing,mid grade or vintage',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            42 => 
            array (
                'id' => '42',
                'geller_sku' => '110062',
                'retail_price' => '$375 ',
                'optionable' => '1',
                'major_item' => 'Dial Service',
                'description' => 'Complete Dial Refinishing, Basic Rolex/high end watches',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            43 => 
            array (
                'id' => '43',
                'geller_sku' => '110063',
                'retail_price' => '$1,125 ',
                'optionable' => '1',
                'major_item' => 'Dial Service',
                'description' => 'Complete Dial Refinishing other brands-By estimate',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            44 => 
            array (
                'id' => '44',
                'geller_sku' => '110100',
                'retail_price' => '$38 to $50',
                'optionable' => '1',
                'major_item' => 'Stems & Crowns',
                'description' => 'Generic dustproof',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            45 => 
            array (
                'id' => '45',
                'geller_sku' => '110101',
                'retail_price' => '$63 to $88',
                'optionable' => '1',
                'major_item' => 'Stems & Crowns',
                'description' => 'Screw down crown plus case tube',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            46 => 
            array (
                'id' => '46',
                'geller_sku' => '110102',
                'retail_price' => 'Estimate Only',
                'optionable' => '1',
                'major_item' => 'Stems & Crowns',
                'description' => 'Original Manufacture\'s Crowns',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            47 => 
            array (
                'id' => '47',
                'geller_sku' => '110103',
                'retail_price' => '$63 to $88',
                'optionable' => '1',
                'major_item' => 'Crown & Stem Combination',
                'description' => 'Generic dustproof',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            48 => 
            array (
                'id' => '48',
                'geller_sku' => '110104',
                'retail_price' => 'Estimate Only',
                'optionable' => '1',
                'major_item' => 'Crown & Stem Combination',
                'description' => 'Screw down crown plus case tube',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Stem broken off in movement of a quartz watch may require replacing the movement',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => 'Stem broken off in movement of a quartz watch may require replacing the movement',
                'created_at' => '',
                'updated_at' => '',
            ),
            49 => 
            array (
                'id' => '49',
                'geller_sku' => '110105',
                'retail_price' => '$115 ',
                'optionable' => '1',
                'major_item' => 'Pusher Button for Chronograph',
                'description' => 'Generic pushers for Chronographs  ',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            50 => 
            array (
                'id' => '50',
                'geller_sku' => '110106',
                'retail_price' => 'Estimate Only',
                'optionable' => '1',
                'major_item' => 'Pusher Button for Chronograph',
                'description' => 'Brand name pushers for Chronographs',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            51 => 
            array (
                'id' => '51',
                'geller_sku' => '110150',
                'retail_price' => '$313 ',
                'optionable' => '1',
                'major_item' => 'Movement Overhaul & Replacement',
                'description' => 'Replace Quartz Movements ',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            52 => 
            array (
                'id' => '52',
                'geller_sku' => '110151',
                'retail_price' => '$463 ',
                'optionable' => '1',
                'major_item' => 'Movement Overhaul & Replacement',
                'description' => 'Non Chrono Quartz Movment Overhaul ',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            53 => 
            array (
                'id' => '53',
                'geller_sku' => '110152',
                'retail_price' => '$663 ',
                'optionable' => '1',
                'major_item' => 'Movement Overhaul & Replacement',
                'description' => 'Chrono Quartz Movment Overhaul ',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            54 => 
            array (
                'id' => '54',
                'geller_sku' => '110153',
                'retail_price' => '$813 ',
                'optionable' => '1',
                'major_item' => 'Movement Overhaul & Replacement',
                'description' => 'Accutron Vintage Tuning Fork,parts are not readily available',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            55 => 
            array (
                'id' => '55',
                'geller_sku' => '110154',
                'retail_price' => '$463 ',
                'optionable' => '1',
                'major_item' => 'Movement Overhaul & Replacement',
                'description' => 'Mechanical Movment Overhaul, low end',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            56 => 
            array (
                'id' => '56',
                'geller_sku' => '110155',
                'retail_price' => '$625 ',
                'optionable' => '1',
                'major_item' => 'Movement Overhaul & Replacement',
                'description' => 'Mechanical Movment Overhaul,mid range: Tag
,Tissot
,Oris
,BM',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            57 => 
            array (
                'id' => '57',
                'geller_sku' => '110156',
                'retail_price' => '$1,125 ',
                'optionable' => '1',
                'major_item' => 'Movement Overhaul & Replacement',
                'description' => 'Mechanical Movment Overhaul, high End',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            58 => 
            array (
                'id' => '58',
                'geller_sku' => '110175',
                'retail_price' => '$688 ',
                'optionable' => '1',
                'major_item' => 'Mechanical Movement Overhaul',
                'description' => 'Rolex Air King, Auto and Bubbleback',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',

                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            59 => 
            array (
                'id' => '59',
                'geller_sku' => '110176',
                'retail_price' => '$875 ',
                'optionable' => '1',
                'major_item' => 'Mechanical Movement Overhaul',
                'description' => 'Rolex Datejust',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            60 => 
            array (
                'id' => '60',
                'geller_sku' => '110177',
                'retail_price' => '$975 ',
                'optionable' => '1',
                'major_item' => 'Mechanical Movement Overhaul',
                'description' => 'Rolex Submariner',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            61 => 
            array (
                'id' => '61',
                'geller_sku' => '110178',
                'retail_price' => '$1,063 ',
                'optionable' => '1',
                'major_item' => 'Mechanical Movement Overhaul',
                'description' => 'Rolex Presidential',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            62 => 
            array (
                'id' => '62',
                'geller_sku' => '110179',
                'retail_price' => '$625 ',
                'optionable' => '1',
                'major_item' => 'Mechanical Movement Overhaul',
                'description' => 'Rolex Manual Wind, Vintage',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            63 => 
            array (
                'id' => '63',
                'geller_sku' => '110180',
                'retail_price' => '$1,063 ',
                'optionable' => '1',
                'major_item' => 'Mechanical Movement Overhaul',
                'description' => 'Rolex GMT',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            64 => 
            array (
                'id' => '64',
                'geller_sku' => '110181',
                'retail_price' => '$138 ',
                'optionable' => '1',
                'major_item' => 'Mechanical Movement Overhaul',
                'description' => 'Eco Drive watches- capacitor Replacement ',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            65 => 
            array (
                'id' => '65',
                'geller_sku' => '110200',
                'retail_price' => '$138 ',
                'optionable' => '1',
                'major_item' => 'Miscellaneous Watch Repairs',
                'description' => 'Eco Drive watches- capacitor Replacement',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            66 => 
            array (
                'id' => '66',
                'geller_sku' => '110201',
                'retail_price' => '$313 ',
                'optionable' => '1',
                'major_item' => 'Miscellaneous Watch Repairs',
                'description' => 'Replace Quartz Movements ',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            67 => 
            array (
                'id' => '67',
                'geller_sku' => '110201',
                'retail_price' => '$463 ',
                'optionable' => '1',
                'major_item' => 'Miscellaneous Watch Repairs',
                'description' => 'Non Chrono Quartz Movment Overhaul ',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            68 => 
            array (
                'id' => '68',
                'geller_sku' => '110202',
                'retail_price' => '$663 ',
                'optionable' => '1',
                'major_item' => 'Miscellaneous Watch Repairs',
                'description' => 'Chrono Quartz Movment Overhaul ',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            69 => 
            array (
                'id' => '69',
                'geller_sku' => '110203',
                'retail_price' => '$813 ',
                'optionable' => '1',
                'major_item' => 'Miscellaneous Watch Repairs',
                'description' => '"Accutron Vintage Tuning Fork',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => 'parts not always redily available',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            70 => 
            array (
                'id' => '70',
                'geller_sku' => '110204',
                'retail_price' => '$463 ',
                'optionable' => '1',
                'major_item' => 'Miscellaneous Watch Repairs',
                'description' => 'Mechanical Movment Overhaul,lower end',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            71 => 
            array (
                'id' => '71',
                'geller_sku' => '110205',
                'retail_price' => '$625 ',
                'optionable' => '1',
                'major_item' => 'Miscellaneous Watch Repairs',
                'description' => 'Mechanical Movment Overhaul,mid range: TAG,Tissot,Oris,BM',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            72 => 
            array (
                'id' => '72',
                'geller_sku' => '110206',
                'retail_price' => '$1,125 ',
                'optionable' => '1',
                'major_item' => 'Miscellaneous Watch Repairs',
                'description' => 'Mechanical Movment Overhaul, High End',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            73 => 
            array (
                'id' => '73',
                'geller_sku' => '110207',
                'retail_price' => '$138 ',
                'optionable' => '1',
                'major_item' => 'Miscellaneous Watch Repairs',
                'description' => 'Eco Drive watches- capacitor Replacement ',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => 'Price is this OR HIGHER',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            74 => 
            array (
                'id' => '74',
                'geller_sku' => '110208',
                'retail_price' => '0',
                'optionable' => '0',
                'major_item' => 'Miscellaneous Watch Repairs',
                'description' => 'Shipping Charges',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            75 => 
            array (
                'id' => '75',
                'geller_sku' => '110250',
                'retail_price' => '0',
                'optionable' => '0',
                'major_item' => '',
                'description' => '',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => '"UseThisGenericSKUNumberToTakeInAWatchRepairAndFillInTheRetailPriceAtTheWatch,from repairer"',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            76 => 
            array (
                'id' => '76',
                'geller_sku' => '110260',
                'retail_price' => '$480 ',
                'optionable' => '1',
                'major_item' => 'Refinish Rolex Watch Bands',
                'description' => 'Refinish Stainless Steel Rolex case & band',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => 'Most polish on non Rolex watches require brushed & high polish',
                'note_to_show' => 'Most polish on non Rolex watches require brushed & high polish',
                'shop_id' => '',
                'is_david' => true,
                'created_at' => '',
                'updated_at' => '',
            ),
            77 => 
            array (
                'id' => '77',
                'geller_sku' => '110261',
                'retail_price' => '$600 ',
                'optionable' => '1',
                'major_item' => 'Refinish Rolex Watch Bands',
                'description' => 'Refinish 18kt Rolex case & band',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => 'Most polish on non Rolex watches require brushed & high polish',
                'note_to_show' => 'Most polish on non Rolex watches require brushed & high polish',
                'shop_id' => '',
                'is_david' => true,
                'created_at' => '',
                'updated_at' => '',
            ),
            78 => 
            array (
                'id' => '78',
                'geller_sku' => '110262',
                'retail_price' => '$1,080 ',
                'optionable' => '1',
                'major_item' => 'Refinish Rolex Watch Bands',
                'description' => 'Refinish Platinum Rolex case & band',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '0',
                'note' => 'Most polish on non Rolex watches require brushed & high polish',
                'note_to_show' => 'Most polish on non Rolex watches require brushed & high polish',
                'shop_id' => '',
                'is_david' => true,
                'created_at' => '',
                'updated_at' => '',
            ),
            79 => 
            array (
                'id' => '79',
                'geller_sku' => '110263',
                'retail_price' => '$88 ',
                'optionable' => '1',
                'major_item' => 'Polish Cases',
            'description' => 'Stainless Steel Case (or higher)',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => '$35 & up',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
            80 => 
            array (
                'id' => '80',
                'geller_sku' => '110264',
                'retail_price' => '$100 ',
                'optionable' => '1',
                'major_item' => 'Polish Cases',
            'description' => 'Titanium Case (or higher)',
                'each_additional' => '',
                'price_criteria_item' => '',
                'thickness' => '',
                'complication_surcharge' => '',
                'part_cost_note' => '',
                'more_percentage_to_SKU' => '',
                'chapter1100SKUs' => '',
                'is_estimated' => '1',
                'note' => '$40 & Up',
                'shop_id' => '',
                'is_david' => true,
                'note_to_show' => '',
                'created_at' => '',
                'updated_at' => '',
            ),
        ));
        
        
    }
}