<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class Chapter200pricingTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('chapter200pricing')->delete();
        
        \DB::table('chapter200pricing')->insert(array (
            0 => 
            array (
                'id' => 1,
                'geller_sku' => '20000',
                'major_item' => 'Tip',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/need_a_tip.png',
                'no_of_price_criteria_item' => '1',
                'price_criteria_item' => 'Tip',
                'JLRC_labor_torch' => '$20x1.90',
                'JLRC_labor_laser' => '$30x1.90',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'geller_sku' => '20001',
                'major_item' => 'Tip',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/need_a_tip.png',
                'no_of_price_criteria_item' => '2-10',
                'price_criteria_item' => 'Tip',
                'JLRC_labor_torch' => '$20x1.0',
                'JLRC_labor_laser' => '$30x1.00',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'geller_sku' => '20002',
                'major_item' => 'Tip',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/need_a_tip.png',
                'no_of_price_criteria_item' => '>=11',
                'price_criteria_item' => 'Tip',
                'JLRC_labor_torch' => '$20x.40',
                'JLRC_labor_laser' => '$30.00x.40',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'geller_sku' => '20003',
                'major_item' => 'Tip',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/need_a_tip.png',
                'no_of_price_criteria_item' => '1',
                'price_criteria_item' => 'Tip',
                'JLRC_labor_torch' => '$20x2.05',
                'JLRC_labor_laser' => '$30x2.05',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'geller_sku' => '20004',
                'major_item' => 'Tip',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/need_a_tip.png',
                'no_of_price_criteria_item' => '2-10',
                'price_criteria_item' => 'Tip',
                'JLRC_labor_torch' => '$20x1.15',
                'JLRC_labor_laser' => '$30.00x1.15',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'geller_sku' => '20005',
                'major_item' => 'Tip',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/need_a_tip.png',
                'no_of_price_criteria_item' => '>=11',
                'price_criteria_item' => 'Tip',
                'JLRC_labor_torch' => '$20x.60',
                'JLRC_labor_laser' => '$30.00x.60',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'geller_sku' => '20006',
                'major_item' => 'Tip',
                'type' => NULL,
                'karats' => '20ktwg',
                'image' => '/images_200/need_a_tip.png',
                'no_of_price_criteria_item' => '1',
                'price_criteria_item' => 'Tip',
                'JLRC_labor_torch' => '$20x2.40',
                'JLRC_labor_laser' => '$30.00x2.40',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'geller_sku' => '20007',
                'major_item' => 'Tip',
                'type' => NULL,
                'karats' => '20ktwg',
                'image' => '/images_200/need_a_tip.png',
                'no_of_price_criteria_item' => '2-10',
                'price_criteria_item' => 'Tip',
                'JLRC_labor_torch' => '$20x1.55',
                'JLRC_labor_laser' => '$30.00x1.55',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'geller_sku' => '20008',
                'major_item' => 'Tip',
                'type' => NULL,
                'karats' => '20ktwg',
                'image' => '/images_200/need_a_tip.png',
                'no_of_price_criteria_item' => '>=11',
                'price_criteria_item' => 'Tip',
                'JLRC_labor_torch' => '$20x.70',
                'JLRC_labor_laser' => '$30.00x.70',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'geller_sku' => '20009',
                'major_item' => 'Tip',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/need_a_tip.png',
                'no_of_price_criteria_item' => '1',
                'price_criteria_item' => 'Tip',
                'JLRC_labor_torch' => '$20x3.25',
                'JLRC_labor_laser' => '$30.00x3.25',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'geller_sku' => '20010',
                'major_item' => 'Tip',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/need_a_tip.png',
                'no_of_price_criteria_item' => '2-10',
                'price_criteria_item' => 'Tip',
                'JLRC_labor_torch' => '$20x2.30',
                'JLRC_labor_laser' => '$30.00x2.30',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'geller_sku' => '20011',
                'major_item' => 'Tip',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/need_a_tip.png',
                'no_of_price_criteria_item' => '>=11',
                'price_criteria_item' => 'Tip',
                'JLRC_labor_torch' => '$20x1.10',
                'JLRC_labor_laser' => '$30.00x1.10',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'geller_sku' => '21000',
                'major_item' => 'Prong',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/need_a_prong.png',
                'no_of_price_criteria_item' => '1',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x2.30',
                'JLRC_labor_laser' => '$30.00x2.30',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'geller_sku' => '21001',
                'major_item' => 'Prong',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/need_a_prong.png',
                'no_of_price_criteria_item' => '2-10',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x1.45',
                'JLRC_labor_laser' => '$30.00x1.45',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            14 => 
            array (
                'id' => 15,
                'geller_sku' => '21002',
                'major_item' => 'Prong',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/need_a_prong.png',
                'no_of_price_criteria_item' => '>=11',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x.65',
                'JLRC_labor_laser' => '$30.00x.65',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            15 => 
            array (
                'id' => 16,
                'geller_sku' => '21003',
                'major_item' => 'Prong',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/need_a_prong.png',
                'no_of_price_criteria_item' => '1',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x2.75',
                'JLRC_labor_laser' => '$30.00x2.75',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'geller_sku' => '21004',
                'major_item' => 'Prong',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/need_a_prong.png',
                'no_of_price_criteria_item' => '2-10',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x1.60',
                'JLRC_labor_laser' => '$30.00x1.60',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'geller_sku' => '21005',
                'major_item' => 'Prong',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/need_a_prong.png',
                'no_of_price_criteria_item' => '>=11',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x.80',
                'JLRC_labor_laser' => '$30.00x.80',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'geller_sku' => '21006',
                'major_item' => 'Prong',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/need_a_prong.png',
                'no_of_price_criteria_item' => '1',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x4.0',
                'JLRC_labor_laser' => '$30.00x4.0',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'geller_sku' => '21007',
                'major_item' => 'Prong',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/need_a_prong.png',
                'no_of_price_criteria_item' => '2-10',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x2.70',
                'JLRC_labor_laser' => '$30.00x2.70',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'geller_sku' => '21008',
                'major_item' => 'Prong',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/need_a_prong.png',
                'no_of_price_criteria_item' => '>=11',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x1.30',
                'JLRC_labor_laser' => '$30.00x1.30',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            21 => 
            array (
                'id' => 22,
                'geller_sku' => '22100',
                'major_item' => 'Full Prong',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/full_prong.png',
                'no_of_price_criteria_item' => '1',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x3.10',
                'JLRC_labor_laser' => '$30.00x3.10',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            22 => 
            array (
                'id' => 23,
                'geller_sku' => '22101',
                'major_item' => 'Full Prong',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/full_prong.png',
                'no_of_price_criteria_item' => '2-10',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x1.80',
                'JLRC_labor_laser' => '$30.00x1.80',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            23 => 
            array (
                'id' => 24,
                'geller_sku' => '22102',
                'major_item' => 'Full Prong',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/full_prong.png',
                'no_of_price_criteria_item' => '>=11',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x1.10',
                'JLRC_labor_laser' => '$30.00x1.10',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            24 => 
            array (
                'id' => 25,
                'geller_sku' => '22103',
                'major_item' => 'Full Prong',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/full_prong.png',
                'no_of_price_criteria_item' => '1',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x3.95',
                'JLRC_labor_laser' => '$30.00x3.95',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            25 => 
            array (
                'id' => 26,
                'geller_sku' => '22104',
                'major_item' => 'Full Prong',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/full_prong.png',
                'no_of_price_criteria_item' => '2-10',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x2.6',
                'JLRC_labor_laser' => '$30.00x2.60',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            26 => 
            array (
                'id' => 27,
                'geller_sku' => '22105',
                'major_item' => 'Full Prong',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/full_prong.png',
                'no_of_price_criteria_item' => '>=11',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x1.80',
                'JLRC_labor_laser' => '$30.00x1.80',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            27 => 
            array (
                'id' => 28,
                'geller_sku' => '22106',
                'major_item' => 'Full Prong',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/full_prong.png',
                'no_of_price_criteria_item' => '1',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x5.80',
                'JLRC_labor_laser' => '$30.00x5.80',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            28 => 
            array (
                'id' => 29,
                'geller_sku' => '22107',
                'major_item' => 'Full Prong',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/full_prong.png',
                'no_of_price_criteria_item' => '2-10',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x4.10',
                'JLRC_labor_laser' => '$30.00x4.10',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            29 => 
            array (
                'id' => 30,
                'geller_sku' => '22108',
                'major_item' => 'Full Prong',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/full_prong.png',
                'no_of_price_criteria_item' => '>=11',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x3.25',
                'JLRC_labor_laser' => '$30.00x3.25',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            30 => 
            array (
                'id' => 31,
                'geller_sku' => '23000',
                'major_item' => 'V Prong',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/v_prong.png',
                'no_of_price_criteria_item' => '1',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x4.0',
                'JLRC_labor_laser' => '$30.00x4.0',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            31 => 
            array (
                'id' => 32,
                'geller_sku' => '23001',
                'major_item' => 'V Prong',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/v_prong.png',
                'no_of_price_criteria_item' => '2-10',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x2.20',
                'JLRC_labor_laser' => '$30.00x2.20',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            32 => 
            array (
                'id' => 33,
                'geller_sku' => '23002',
                'major_item' => 'V Prong',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/v_prong.png',
                'no_of_price_criteria_item' => '>=11',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x1.80',
                'JLRC_labor_laser' => '$30.00x1.80',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            33 => 
            array (
                'id' => 34,
                'geller_sku' => '23003',
                'major_item' => 'V Prong',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/v_prong.png',
                'no_of_price_criteria_item' => '1',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x4.25',
                'JLRC_labor_laser' => '$30.00x4.25',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            34 => 
            array (
                'id' => 35,
                'geller_sku' => '23004',
                'major_item' => 'V Prong',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/v_prong.png',
                'no_of_price_criteria_item' => '2-10',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x2.60',
                'JLRC_labor_laser' => '$30.00x2.60',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            35 => 
            array (
                'id' => 36,
                'geller_sku' => '23005',
                'major_item' => 'V Prong',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/v_prong.png',
                'no_of_price_criteria_item' => '>=11',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x1.80',
                'JLRC_labor_laser' => '$30.00x1.80',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            36 => 
            array (
                'id' => 37,
                'geller_sku' => '23006',
                'major_item' => 'V Prong',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/v_prong.png',
                'no_of_price_criteria_item' => '1',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x6.10',
                'JLRC_labor_laser' => '$30.00x6.10',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            37 => 
            array (
                'id' => 38,
                'geller_sku' => '23007',
                'major_item' => 'V Prong',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/v_prong.png',
                'no_of_price_criteria_item' => '2-10',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x4.50',
                'JLRC_labor_laser' => '$30.00x4.50',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            38 => 
            array (
                'id' => 39,
                'geller_sku' => '23008',
                'major_item' => 'V Prong',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/v_prong.png',
                'no_of_price_criteria_item' => '>=11',
                'price_criteria_item' => 'Prong',
                'JLRC_labor_torch' => '$20x3.90',
                'JLRC_labor_laser' => '$30.00x3.90',
                'stuller_sku' => NULL,
                'stuller_part_item_if_needed' => NULL,
                'part_cost_note' => NULL,
                'note' => NULL,
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            39 => 
            array (
                'id' => 40,
                'geller_sku' => '24000',
                'major_item' => 'Channel Repair',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/channel_repair.png',
                'no_of_price_criteria_item' => '1-7',
                'price_criteria_item' => 'stone',
                'JLRC_labor_torch' => '$20x2.95',
                'JLRC_labor_laser' => '$30.00x3.90',
                'stuller_sku' => '["BEZEL:9301874:P"]',
                'stuller_part_item_if_needed' => 'BEZEL Strip - Flat',
            'part_cost_note' => '10%(x)',
                'note' => 'Channel repair: do not ORDER this part, use it for parts cost,cost is 10% of the 12" cost per STONE',
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            40 => 
            array (
                'id' => 41,
                'geller_sku' => '24001',
                'major_item' => 'Channel Repair',
                'type' => NULL,
                'karats' => '14kt',
                'image' => '/images_200/channel_repair.png',
                'no_of_price_criteria_item' => '>=8',
                'price_criteria_item' => 'stone',
                'JLRC_labor_torch' => '$20x1.55',
                'JLRC_labor_laser' => '$30.00x1.55',
                'stuller_sku' => '["BEZEL:9301874:P"]',
                'stuller_part_item_if_needed' => 'BEZEL Strip - Flat',
            'part_cost_note' => '10%(x)',
                'note' => 'Channel repair: do not ORDER this part, use it for parts cost,cost is 10% of the 12" cost per STONE',
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            41 => 
            array (
                'id' => 42,
                'geller_sku' => '24002',
                'major_item' => 'Channel Repair',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/channel_repair.png',
                'no_of_price_criteria_item' => '1-7',
                'price_criteria_item' => 'stone',
                'JLRC_labor_torch' => '$20x3.40',
                'JLRC_labor_laser' => '$30.00x3.40',
                'stuller_sku' => '["BEZEL:9301986:P"]',
                'stuller_part_item_if_needed' => 'BEZEL Strip - Flat',
            'part_cost_note' => '10%(x)',
                'note' => 'Channel repair: do not ORDER this part, use it for parts cost,cost is 10% of the 12" cost per STONE',
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            42 => 
            array (
                'id' => 43,
                'geller_sku' => '24003',
                'major_item' => 'Channel Repair',
                'type' => NULL,
                'karats' => '18kt',
                'image' => '/images_200/channel_repair.png',
                'no_of_price_criteria_item' => '>=8',
                'price_criteria_item' => 'stone',
                'JLRC_labor_torch' => '$20x2.05',
                'JLRC_labor_laser' => '$30.00x2.05',
                'stuller_sku' => '["BEZEL:9301986:P"]',
                'stuller_part_item_if_needed' => 'BEZEL Strip - Flat',
            'part_cost_note' => '10%(x)',
                'note' => 'Channel repair: do not ORDER this part, use it for parts cost,cost is 10% of the 12" cost per STONE',
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            43 => 
            array (
                'id' => 44,
                'geller_sku' => '24004',
                'major_item' => 'Channel Repair',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/channel_repair.png',
                'no_of_price_criteria_item' => '1-7',
                'price_criteria_item' => 'stone',
                'JLRC_labor_torch' => '$20x5.40',
                'JLRC_labor_laser' => '$30.00x5.40',
                'stuller_sku' => '["BEZEL:9301938:P"]',
                'stuller_part_item_if_needed' => 'BEZEL Strip - Flat',
            'part_cost_note' => '10%(x)',
                'note' => 'Channel repair: do not ORDER this part, use it for parts cost,cost is 10% of the 12" cost per STONE',
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
            44 => 
            array (
                'id' => 45,
                'geller_sku' => '24005',
                'major_item' => 'Channel Repair',
                'type' => NULL,
                'karats' => 'Platinum',
                'image' => '/images_200/channel_repair.png',
                'no_of_price_criteria_item' => '>=8',
                'price_criteria_item' => 'stone',
                'JLRC_labor_torch' => '$20x2.70',
                'JLRC_labor_laser' => '$30.00x2.70',
                'stuller_sku' => '["BEZEL:9301938:P"]',
                'stuller_part_item_if_needed' => 'BEZEL Strip - Flat',
            'part_cost_note' => '10%(x)',
                'note' => 'Channel repair: do not ORDER this part, use it for parts cost,cost is 10% of the 12" cost per STONE',
                'orderable' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'shop_id' => '',
                'is_david' => true,
                'is_master' => 0,
            ),
        ));
        
        
    }
}